### ISSUE TITLE
UI issue in iPhone11 pro max

### ISSUE THREAD

**Issue by ruchinsomal** [getbouncer/cardscan-ios#105]
Please have a look at the issue in iPhone11 pro max, I am attaching a screenshot for your reference 
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-11 at 17 34 34](https://user-images.githubusercontent.com/12675398/70620197-96181e80-1c3c-11ea-8577-79c15ea65864.png)

**Comment by kingst** [comment]
Which version of the cardscan cocoapod are you using?

**Comment by ruchinsomal** [comment]
CardScan (1.0.5022)

**Comment by jaimejiyepark** [comment]
Hello @ruchinsomal! 
Can you give us more details on how you instantiate the `ScanViewController` so we can reproduce the error? (i.e. pushing it onto a navigation controller, using a zoomed screen)

**Comment by kingst** [comment]
@ruchinsomal is this still an issue for you?

**Comment by pawanline** [comment]
I think , this is resolved now.
