### ISSUE TITLE
Release 1.0.5024 breaks Carthage

### ISSUE THREAD

**Issue by Sidetalker** [getbouncer/cardscan-ios#112]
[Release 1.0.5024](https://github.com/getbouncer/cardscan-ios/releases/tag/1.0.5024) breaks Carthage compatibility. 

Carthage error message: `Dependency "cardscan-ios" has no shared framework schemes for any of the platforms: iOS`

I may have time to look at this myself, just wanted to file an issue asap - for the time being I'm using 1.0.5023.

**Comment by jaimejiyepark** [comment]
Hello! Have you tried re-clicking `shared` in your project schemes in your workspace then building?

**Comment by kingst** [comment]
@Sidetalker I'm going to close this, please let us know if you are still having issues.

**Comment by cmvagner** [comment]
I'm having the same issue.
Release 1.0.5023 does work with Carthage.

**Comment by cmvagner** [comment]
In version 1.0.5024 "Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/CardScan.xcscheme" was removed. I can't find any other shared scheme checked into the repo which Carthage can use.

**Comment by jaimejiyepark** [comment]
We're sorry about that! Our carthage build does seem to break in this version. If you don't mind, we have a more updated version available for you to use: version 1.0.5028.

**Comment by cmvagner** [comment]
I'm still getting ```Dependency "cardscan-ios" has no shared framework schemes for any of the platforms: iOS``` for version 1.0.5028.

**Comment by jaimejiyepark** [comment]
Hello @cmvagner and @Sidetalker!

**Comment by cmvagner** [comment]
Hello @jaimejiyepark 
Just tried building with Carthage using latest commit 613afb948185d211fdee1cf3a6103cb841df11c0 and now it works. Thank you!
