### ISSUE TITLE
ScanViewController is not opening on iPhone 6 and iPhone6plus real device iOS version 12.4

### ISSUE THREAD

**Issue by pawanline** [getbouncer/cardscan-ios#115]
Please look into this asap.
<img width="1440" alt="Screenshot 2020-01-30 at 10 40 37 PM" src="https://user-images.githubusercontent.com/15170689/73473406-b8aff380-43b2-11ea-9da6-26432ccc4bc8.png">

**Comment by jaimejiyepark** [comment]
Hello @pawanline,
Can you tell me what CardScan version you are using and any error messages if you got any?

**Comment by pawanline** [comment]
latest I guess , pod 'CardScan' xcode 11.2.1

**Comment by pawanline** [comment]
I am getting this on cosole 
   print("This device is incom patible with CardScan")

**Comment by jaimejiyepark** [comment]
Just making sure but do you have this in your configuration before you instantiate the view controller? This allows scanViewController to be used with older devices.

```  
...
let config = ScanConfiguration()
config.runOnOldDevices = true
guard let vc = ScanViewController.createViewController(withDelegate: self, configuration: config) else { 
    print("scan view controller not supported on this hardware")
    return
}

```
