### ISSUE TITLE
all non embosed card not getting scan only some are working

### ISSUE THREAD

**Issue by keyurpatel4707** [getbouncer/cardscan-ios#130]
I downloaded your iOS demo. all non embosed card not getting scan only some are working. can you please check because for android it is working fine for all card.

**Comment by kingst** [comment]
Would you mind posting a picture of a card that doesn't work? I'd black out the everything except the last 4 digits.

However, the Android OCR model is a bit ahead of our iOS model, so I'm not surprised that it's performing a bit better.

**Comment by kingst** [comment]
I can't commit to specific timing for the new OCR model to come to iOS, but it'll happen as soon as we get enough data to confirm that it's working well and that we have a model for extracting expiry well with the new model (Android currently doesn't have expiry support, which iOS does have)

**Comment by kingst** [comment]
Marking as closed, we improved our OCR recently I'd check out the master branch to see if it improves things for you.
