### ISSUE TITLE
CardScan class same name as module CardScan

### ISSUE THREAD

**Issue by arbitur** [getbouncer/cardscan-ios#134]
I just updated from an older version (from october) to the previous version `1.0.5029` and I get a new error caused by name conflicts.

In my app I have a custom class called `CreditCard` (same as in module CardScan) so I have to distinguish them apart by prefixing `CardScan.CreditCard`.

The problem now is I see a new class (introduced in #114) `CardScan`.

This breaks my code and I can no longer distinguish my `CreditCard` class apart from yours.

Don't name `classes/structs/enums` the same name as your module, bad practice.

I have downgraded to `1.0.5027` as for now until this problem gets fixed.

**Comment by kingst** [comment]
@jaimejiyepark we're using the CardScan class only for handling bundle updates, and I believe that we have only one app using this thus far so it is safe to change. I think this is a reasonable request, can you pick this up?

**Comment by jaimejiyepark** [comment]
Hello @arbitur,
Thank you for bringing this up with us. 
I wanted to let you know that the CardScan class name change is pushed to master.
