### ISSUE TITLE
Sometime getting wrong valid thru or expire date 

### ISSUE THREAD

**Issue by priyankastridhyatech** [getbouncer/cardscan-ios#141]
Hello team,

I am facing issue while i am scanning emboss card will not get right expire date

**Comment by kingst** [comment]
Would you mind sharing an image of your card that it's struggling with? Which version of the library are you using? We did make some adjustments in version `1.0.5029` to address this (https://github.com/getbouncer/cardscan-ios/blob/master/CHANGELOG.md#105029-2020-02-11)

But, this is still a known issue and something that we're actively working on. Hang tight for a week or two and we'll hopefully have something better if you are already on 1.0.5029 or greater.
