### ISSUE TITLE
Card Type in iOS

### ISSUE THREAD

**Issue by mramesh528** [getbouncer/cardscan-ios#152]
Hi Team,

Please can you let me know how to get card type in iOS, in android we have network as a field to get the card type.

**Comment by kingst** [comment]
for iOS you can call this utility function to get the card network:

https://github.com/getbouncer/cardscan-ios/blob/8e99e843dc5e8309eb27fe2226754cb07bd19aa2/CardScan/Classes/CreditCardUtils.swift#L227

**Comment by kingst** [comment]
Marking as closed, @mramesh528 let us know if you need any further clarification or if I missed something.
