### ISSUE TITLE
Scan View Controller Localization

### ISSUE THREAD

**Issue by ercillagorka** [getbouncer/cardscan-ios#18]
Hi!
Could you add some initialization or method to change the texts in Scan View Controller?
Thanks!

**Comment by kingst** [comment]
We have one already -- we just haven't added documentation. If you implement the [ScanStringsDataSource](https://github.com/getbouncer/cardscan-ios/blob/054d977bad2910c2d73632934f7169e82ec49069/CardScan/Classes/ScanViewController.swift#L27) protocol you can customize the strings.

You can see an example of how to use this protocol [here](https://github.com/getbouncer/cardscan-ios/blob/054d977bad2910c2d73632934f7169e82ec49069/Example/CardScan/ViewController.swift#L71).

**Comment by ercillagorka** [comment]
Sorry, I had an old version of the pod and did not find it.
Thank you!
