### ISSUE TITLE
Update payment systems

### ISSUE THREAD

**Issue by akhakimzyanov** [getbouncer/cardscan-ios#202]
We have trouble, that card with prefix number 2200 doesn't recognizing. It is Russian payment system, prefix = 220. Can you add it please to CardUtils for recognizing. https://en.wikipedia.org/wiki/Mir_(payment_system)

**Comment by akhakimzyanov** [comment]
Here is list of actual card numbers https://en.wikipedia.org/wiki/Payment_card_number

**Comment by kingst** [comment]
This is a reasonable request, let me propose something and get your feedback

**Comment by kingst** [comment]
We added an explicit `addMirSupport` function to the `CreditCardUtils` class in addition more general support for regional cards, it'll be in our next release. Thanks for the feedback!

**Comment by akhakimzyanov** [comment]
Thanks! Nice solution!
