### ISSUE TITLE
Can I custmor card type?

### ISSUE THREAD

**Issue by kaneli8759** [getbouncer/cardscan-ios#218]
Can I custmor card type?
like this... 
123456 000000 999999

**Comment by awushensky** [comment]
Hi @kaneli8759 , you can add support for any regional cards by calling `CreditCardUtils.prefixesRegional += ["123456"]`. This will support scanning cards that begin with `123456` and pass the luhn check.

**Comment by kaneli8759** [comment]
@awushensky thanks for reply
And I have another question.
I need to recognize 16 to 18 digits, but doesn’t need to follow the luhn algorithm

Is there a way to simply identify 16 to 18 digits?

**Comment by awushensky** [comment]
Hi @kaneli8759 , unfortunately we use the Luhn check to verify the accuracy of the scan, so we are not able to just scan digits without some form of check.

**Comment by kaneli8759** [comment]
> 嗨，@ kaneli8759，您好，我們使用Luhn檢查來驗證掃描的準確性，因此，如果不進行某種形式的檢查，我們將無法僅掃描數字。

ok. thank you  very much for reply
