### ISSUE TITLE
Can not edit any thing 

### ISSUE THREAD

**Issue by AhmadOdeh93** [getbouncer/cardscan-ios#22]
hey, 
first thanks very much this library awesome 
i need any advice to edit some points :
1- Hide flash button or change the icon .
2- change the corner radius for indicator in the corner focus area , and change color of it .
3- this point very important any way to hide the text (numbers & expiry date) after catch the info from card , i mean when catch the card number the number show before dismiss .
4- change the font and change labels properties like (lines number) .
i’m sorry to ask many questions, but i think it’s important, any advice to edit or change it please .

**Comment by kingst** [comment]
For changing fonts we do have the ability to customize these, we just pushed a release today that handles it. In terms of the flash light button and corners, did you have an example of what you want to change it to?

Showing the number is a fairly important part of the user experience for most apps because we continue to scan while doing error correction after we capture the first number. Without showing the number we would need to have some other indicator of progress. Did you have something in particular in mind?

**Comment by AhmadOdeh93** [comment]
thank you for fas response , you can check image below please , i show on it what i want change , first border color or width , about the green corner i want change the color , about flash light button i can hide it ? about showing the number i'm with you its important part but i mean just hide the label or make the color clear .

<img width="409" alt="Screenshot 2019-06-19 at 10 14 39" src="https://user-images.githubusercontent.com/30660018/59744654-b6fa4b00-927b-11e9-8a48-98d3a467e55c.png">
![Simulator Screen Shot - iPhone Xs Max - 2019-06-19 at 10 08 37](https://user-images.githubusercontent.com/30660018/59744655-b792e180-927b-11e9-966a-74fac95710ac.png)

**Comment by kingst** [comment]
Thanks for the feedback! I don't think we'll be able to do this now, but we'll add it to our backlog!

**Comment by AhmadOdeh93** [comment]
Thank you , but you can’t give me any hint to do this ? i tried change it or hidden from storyboard and from the code but nothing change

**Comment by kingst** [comment]
Most of our UI is in the storyboard, but the two parts that are in code are (1) the mask layer with tinted background and a clear hole for the card and (2) the corners. So if you want to change most UI elements it's done through the storyboard but the mask and corners are in code. I'm closing this issue, but let me know if you need any more help.

**Comment by LusineSargsyan** [comment]
Hi I'm trying to customize texts but it's not possible (, is there any way to customize for localization?

**Comment by LusineSargsyan** [comment]
oh, sorry I find answer for my question ). thank you
for others who will have same issue ) you should conform protocol ScanStringsDataSource
