### ISSUE TITLE
Enhancement: right bar button item

### ISSUE THREAD

**Issue by nickjf89** [getbouncer/cardscan-ios#226]
We are using CardScan in our app, and we are presenting the `ScanViewController` modally, embedded in a navigation controller. The navigation controller is hidden by `ScanViewController`, which is understandable, but our app has rules around modally presented view controllers whereby we always show an X button to close in the top right. Obviously, you provide a back button (outside of a navigation item) on the left side of the view controller, and it would be great to have the flexibility to choose where this is positioned (left or right), and an image for the button.

**Comment by kingst** [comment]
Check out our [UI Customization docs](https://docs.getbouncer.com/card-scan/ios-integration-guide/ios-customization-guide), you may want to consider using the `SimpleScanViewController` which we designed for full UI customization.

Do you think this will work for you?

**Comment by nickjf89** [comment]
Thank, I'll take a look. Does this allow us to set an image on the torch button, or just text? And also, will the back button chevron still be visible if we provide no string for that button?

**Comment by kingst** [comment]
You should be able to change everything to customize it for your needs. Let us know in Slack if you have any questions.

**Comment by kingst** [comment]
Closing this issue, please let us know if you still have questions on UI customization -- happy to help
