### ISSUE TITLE
Add Support to Swift Package Manager

### ISSUE THREAD

**Issue by julioarregoitia** [getbouncer/cardscan-ios#228]
It's pretty simple my issue. Just add support to Swift Package Maneger. Best regards.

**Comment by jaimejiyepark** [comment]
Hello!
We are currently working to have automation in place to test all of our dependency manager support. Once we can test cocoapods and carthage automatically, then we'll work on adding SPM support. 

We're a really small team so it may take some time for this support to land but SPM support will come!

Thank you for understanding!

**Comment by julioarregoitia** [comment]
Okey thanks. I understand. Happy coding.
