### ISSUE TITLE
Why restrict iOS version to iOS 11.2+

### ISSUE THREAD

**Issue by jessehao** [getbouncer/cardscan-ios#234]
In `ScanBaseViewController.captureOutputWork(sampleBuffer:)` - line 342, there is an iOS version constraint and I cannot figure it why.

And I can't found any calls to iOS 11.2+ API of `SSDCreditCardOcr`.
So why there is an iOS 11.2+ Constraint ?

**Comment by kingst** [comment]
At some point there is a call to CoreML models which require iOS 11.2+, and the compiler surfaces these all the way up statically.

**Comment by jessehao** [comment]
What would happen if I use this in iOS 11.0 without the constraint? crash or nothing happens?

I don't have any devices runs on iOS 11.0 😓

**Comment by kingst** [comment]
Fortunately not many people have devices that run iOS 11.0 :)

We don't allow you to create a ViewController if your device is unsupported, you can see this [here](https://github.com/getbouncer/cardscan-ios/blob/9c8e4215e54d999b2621af12aed1e91c339aacd0/CardScan/Classes/ScanViewController.swift#L146) with our `ScanViewController` and [here](https://github.com/getbouncer/cardscan-ios/blob/9c8e4215e54d999b2621af12aed1e91c339aacd0/CardScan/Classes/SimpleScanViewController.swift#L66) with our `SimpleScanViewController`.

**Comment by kingst** [comment]
Closing this issue, please let us know if you'd like further clarification
