### ISSUE TITLE
Card Prefixes for Uzbekistan Cards

### ISSUE THREAD

**Issue by dilshodzopirov** [getbouncer/cardscan-ios#239]
Can you please add "8" and "9" prefixes to CreditCardUtils? In Uzbekistan card numbers starts with "8" and "9"

**Comment by kingst** [comment]
Hi @dilshodzopirov You can set the appropriate prefixes using our `regional prefixes` feature: https://docs.getbouncer.com/card-scan/ios-integration-guide/card-support#adding-regional-issuers

As long as these cards pass the Luhn check and are 16 digits this should be all you need to support Uzbekistan cards.

**Comment by kingst** [comment]
Let us know if you have any further questions by re-opening this issue. From what I can tell your regional issuers feature should support your use case, so I'm closing this issue.
