### ISSUE TITLE
Rare crash on an iPhone SE(2nd Generation) 

### ISSUE THREAD

**Issue by julioarregoitia** [getbouncer/cardscan-ios#261]
Hello, i have this strange crash with the flag SIGABART(in DEBUG mode) when I try to assign any value to the instance of `ScanViewController` (CardScan version 2.0.7).

![Captura de Pantalla 2021-02-18 a la(s) 1 43 00 a  m](https://user-images.githubusercontent.com/35386842/108316235-a3a72d80-718a-11eb-85f9-ab08e375a0cc.png)

That only happen in a real device, the iPhone SE(2nd Generation), iOS 14.4 . I already tried with the Simulator and an iPhone 12(iOS 14.4 too) but nothing bad happens. The crash only happens on the iPhone SE. 

By the way it works fine and displays correctly if I type the following

```
    func recognizerScanCard() -> ScanViewController?
    {
        guard let vc = ScanViewController.createViewController(withDelegate: self) else {
            return nil
        }
        
        // vc.stringDataSource = self
        // vc.cornerColor = UIColor(hexString: "002BD9")
        // vc.allowSkip = true
        
        return vc
        
    }

    @IBAction func buttonScanCardPressed(_ sender: AnimatableButtonCustomized)
    {
        if let vc = self.recognizerScanCard() {
            self.present(vc, animated: true, completion: nil)
        }
        
    }
```

Best regards

**Comment by kingst** [comment]
Hi @julioarregoitia I'm going to take this issue on personally. I have an iPhone SE 2nd generation, let me spin it up and see if I can reproduce your crash.

**Comment by kingst** [comment]
@julioarregoitia I tried it out on my iPhone SE (2nd generation) and it worked fine. Can you send us more information about the crash itself? The screen shot doesn't say anything about why it crashed.

**Comment by julioarregoitia** [comment]
Don't worry then. I put a try-catch with the help off Objective-C, so just keep working in your things. Thanks for the hard work. Best regards
