### ISSUE TITLE
QUESTION / ENHANCEMENT: Deny certain fields from being scanned

### ISSUE THREAD

**Issue by sha8wn** [getbouncer/cardscan-ios#262]
Hello CardScan team,

I have the SDK up and running and it works well.

I am not sure if this is the right place to ask this, but right now when I scan the credit card, it scans all the relevant data as expected.

However, for my application, I only need the CC number. While I can handle that on the UI side of my app to show only the relevant fields, for a brief moment, on the Card Scanner Controller, it does show that the expiry was scanned as well which might make the user's wonder, why am I scanning this data if I do not need it.

So I was wondering if there was a way to specify what fields we were interested in scanning ?

Thanks in advance.

**Comment by kingst** [comment]
Which ViewController are you using? There should be a way to customize the UI that we provide to have the same net effect of what you're looking for, but it's a little different between `ScanViewController` and `SimpleScanViewController`

**Comment by sha8wn** [comment]
I am using CardScan via VGS so what I use is something called ```VGSCardScanController```. I believe under the hood it is using ```ScanViewController```

**Comment by kingst** [comment]
Hi @sha8wn from a systems and efficiency perspective we would run the exact same machine learning even if you were interested in only the card number. Are you looking for a way to hide the expiry UI view when the scanning process is happening, or were you more interested in improved performance due to scanning fewer entities?

**Comment by sha8wn** [comment]
Hello @kingst - for my application, the performance seems fine, hiding the view should suffice for now.

**Comment by kingst** [comment]
Closing this issue as there hasn't been any activity on it for a while. Please re-open this if this continues to be a problem.
