### ISSUE TITLE
No such module 'CardScan'

### ISSUE THREAD

**Issue by mihirmodiofficial** [getbouncer/cardscan-ios#267]
In iOS after installing latest version pods, Its showing error "No such module 'CardScan'"
latest version is '2.0.3'
previous version '1.0.5032' was not showing the above error

**Comment by jaimejiyepark** [comment]
Hello @mihirmodiofficial,
I would love to help you out. Does the error persist after you clean + build your project?

**Comment by mihirmodiofficial** [comment]
Yes i tried but the error is still showing

**Comment by jaimejiyepark** [comment]
Interesting. I was able to build and run `CardScan 2.0.3` with XCode 11.  Can I see your Podfile?

**Comment by kingst** [comment]
It looks like this issue hasn't had any activity in a while, I'm closing it for now but please re-open it if this continues to be problematic.

**Comment by kishinmanglani** [comment]
Also having this issue
