### ISSUE TITLE
Name and expiry not picking

### ISSUE THREAD

**Issue by watheeq123** [getbouncer/cardscan-ios#284]
I am trying the demo project but the Name and expiry not picking. Any help?

**Comment by kingst** [comment]
Name and expiry are only supported on iOS 13+. If your device is running iOS 13 or higher, you can try setting the `scanPerformancePriority` property on the `SimpleScanViewController` to `.accurate`. It defaults to `.fast`, which prioritizes scanning the card number quickly over scanning all card details.

**Comment by kingst** [comment]
Also, here is a link to our docs where we explain it in more detail: https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/ios-integration-guide/advanced-customization#configuration

**Comment by watheeq123** [comment]
I am on ios 14.5.1 but will try changing the setting and let you know.
