### ISSUE TITLE
Trying to scan the card but app crashes in iPhone 8

### ISSUE THREAD

**Issue by iosdevronak** [getbouncer/cardscan-ios#290]
I have implemented this code and while running app on iPhone 11 its working properly, scans card number , expiry month and expiry year. But when running app in iPhone 8 while scanning I only get the card number and expiry year & month is getting nil.
Is this issue is device specific?

**Comment by kingst-stripe** [comment]
Try switching to [accurate mode](https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/ios-integration-guide/advanced-customization), it'll help a lot with older phones.

With that being said I wouldn't expect to get the expiry or name every time, but with accurate mode you'll get it more often on old devices.

**Comment by kingst-stripe** [comment]
Closing this issue, please re-open this ticket if accurate mode doesn't help
