### ISSUE TITLE
Feature Request: Mac OS Catalyst Compatibility  

### ISSUE THREAD

**Issue by cvcoder1** [getbouncer/cardscan-ios#291]
If you could please enable Mac OS Catalyst Compatibility, as the Stripe cocoa pods library has, that would be greatly appreciated. Cheers from Belgium :)

**Comment by kingst-stripe** [comment]
Thanks for reaching out, @cvcoder1! We have a few internal Mac Catalyst apps that use this, but we haven't put it into our production pipeline yet. Once we're fully integrated with Stripe we will support Mac Catalyst, but for now you'll have to build it yourself and copy the xcframework in manually. Let us know if you'd like feedback on how to do this, but it involves downloading our code and building the example app with Mac Catalyst enabled.

**Comment by thecavilnator** [comment]
I think this has been completed.
