### ISSUE TITLE
Carthage failed with exit code 74

### ISSUE THREAD

**Issue by RobertMietelski** [getbouncer/cardscan-ios#293]
I would like to add the `cardscan-ios` library to my project using Carthage. I used the example found [here](https://github.com/getbouncer/cardscan-carthage-example)
After running `carthage update` command in terminal I get error:
```
A shell task (/usr/bin/xcrun xcodebuild -project /Users/robertmietelski/Desktop/Test/Carthage/Checkouts/cardscan-ios/SpmXCFrameworkTest/SpmXCFrameworkTest.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Could not resolve package dependencies:
  Failed to clone repository /Users/kingst/work/cardscan-ios:
    fatal: repository '/Users/kingst/work/cardscan-ios' does not exist
```
<img width="568" alt="Zrzut ekranu 2021-12-29 o 09 29 42" src="https://user-images.githubusercontent.com/9719324/147642424-bfacb119-fc21-40e1-bbb7-147751f73734.png">

Does anyone know how to fix this?

**Comment by kingst-stripe** [comment]
Hi @RobertMietelski, we dropped support for Carthage with our version 2 release. If CocoaPods and Swift Package Manager don't work for you, you should be able to load our release binary into your project manually. You can find it by navigating to a release tag in github and pulling the URL out of the `Package.swift` file. Here is the [`Package.swift` file for release 2.1.2](https://github.com/getbouncer/cardscan-ios/blob/2.1.2/Package.swift)
