### ISSUE TITLE
Crashes on SwiftUI

### ISSUE THREAD

**Issue by pooja1bhatia** [getbouncer/cardscan-ios#295]
Hii,

This library works fine for storyboard projects, but it crashes in SwiftUI. I integrated ScanViewController in swiftUI by using UIViewControllerRepresentable. But when I click on the button to open it the App crashes. 

I’m attaching my scanner file.Please review it and let me know if I’m doing something wrong.

[CardScanner.swift.zip](https://github.com/getbouncer/cardscan-ios/files/9316400/CardScanner.swift.zip)

**Comment by jaimepark-stripe** [comment]
Hello @pooja1bhatia! 
Thank you for the example file you provided. Let me try to reproduce the crash you mentioned and get back to you. 
Do you mind providing me the iOS and XCode version you used?

**Comment by pooja1bhatia** [comment]
Hii @jaimepark-stripe 
Xcode version is 13.1
Mac OS Version is 11.6.1
iOS version is 15.2

**Comment by pooja1bhatia** [comment]
The issue is fixed by replacing ScanViewController() to ScanViewController.createViewController(withDelegate: nil)
Thanks!
