### ISSUE TITLE
Error in declaring network.

### ISSUE THREAD

**Issue by dominiquealexi** [getbouncer/cardscan-ios#35]
Most of our users are getting a crash with this error. I can run it fine on my device, and my handful of testers can run the application just fine.

Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.apple.CoreML Code=0 "Error in declaring network." UserInfo={NSLocalizedDescription=Error in declaring network.}: file **[path to project]**/Pods/CardScan/CardScan/Classes/Models.swift, line 274
--

Any help would be appreciated!

**Comment by kingst** [comment]
Which version of the library are you using? We discovered this a few weeks ago and put out a fix. The latest version of the library, version 1.0.4059, should contain the bug fix.

To trigger the bug you have to put your app in the background immediately after launching it. There is a rare race condition that can happen when the machine learning models initialize when the app is in the background.

Here are all of the PRs that show our fixes + improvements to testing infrastructure, in case you are interested:

https://github.com/getbouncer/cardscan-ios/pull/31
https://github.com/getbouncer/cardscan-ios/pull/30
https://github.com/getbouncer/cardscan-ios/pull/29
https://github.com/getbouncer/cardscan-ios/pull/28
https://github.com/getbouncer/cardscan-ios/pull/27
https://github.com/getbouncer/cardscan-ios/pull/26
https://github.com/getbouncer/cardscan-ios/pull/25

**Comment by dominiquealexi** [comment]
We were using 1.0.4049! Just upgraded to 1.0.4059 and will see what happens. Thank you!

**Comment by kingst** [comment]
Great, please do keep me updated either way. BTW: I'm surprised that most of your users are seeing the crash, in our experience it should have been between 0.2% and 0.6%. Would you be open to chatting on slack so I can get a little more information?

https://getbouncer.slack.com/messages/CDQ8ULAL9/convo/GK1N3GC66-1561853894.120200/

**Comment by dominiquealexi** [comment]
Can't seem to access that--my email is my username here @ gmail :)

**Comment by kingst** [comment]
Closing out this issue, based on slack chat this is the same issue we saw previously. Please do re-open this issue if you see any more crashes.
