### ISSUE TITLE
How can I import the Stripe functionality using Carthage

### ISSUE THREAD

**Issue by Sidetalker** [getbouncer/cardscan-ios#72]
After integrating CardScan via Carthage I found myself unable to access the Stripe extension - is this something I can do via Carthage?

**Comment by kingst** [comment]
We're still very new to Carthage so there is probably a dependency that we need to setup to enable it. With cocoapods it was easy to have an optional dependency on Stripe, but we haven't looked into how to do it yet.

For the time being here is a [link to the function](https://github.com/getbouncer/cardscan-ios/blob/da77e36c49f1de4b678e7ecaab56cc1466602716/CardScan/Classes/ScanViewController.swift#L58), you can add an extension to the CreditCard object in your code, but give us some time to look into how to support this.

If you're experienced with Carthage and up for submitting a PR we'd love it!

**Comment by Sidetalker** [comment]
Thanks @kingst! I'll close this issue and will open up a PR if I find a way to make it work with Carthage.

**Comment by collinvargo** [comment]
I'm getting no such module errors for 'import CardScan' after upgrading CardScan to latest version. Can't find anything about this in the documentation as it's a well overdue update... any help?

**Comment by kingst** [comment]
Hi Collin, Are you using Carthage? If so, we dropped support for it when we updated to our 2.0 version. We support:

- Swift Package Manager
- Cocoapods
- Manual installation by dragging and dropping our xcframework

Here is a link to our [docs](https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/ios-integration-guide#installation) for more information.

**Comment by collinvargo** [comment]
No. We're using pods & the stripe extension, actually. I was able to get it working. It was just a pod dein issue, luckily.

**Comment by collinvargo** [comment]
> Hi Collin, Are you using Carthage? If so, we dropped support for it when we updated to our 2.0 version. We support:
> 
>     * Swift Package Manager
> 
>     * Cocoapods
> 
>     * Manual installation by dragging and dropping our xcframework
> 
> 
> Here is a link to our [docs](https://docs.getbouncer.com/bouncer-scan/credit-card-ocr/ios-integration-guide#installation) for more information.

Thanks for the timely reply and the resources :) Have a great weekend.
