### ISSUE TITLE
Code is Swift 2.x and not 4

### ISSUE THREAD

**Issue by josher93** [getbouncer/cardscan-ios#75]
I'm trying to install ScanCard in my project written in Objective-C. I installed the pod and when I open my workspace I get this message:

> **Unsupported Swift Version**
> The target “CardScan” contains source code developed with Swift 2.x. This version of Xcode does not support building or migrating Swift 2.x targets.
> 
> Use Xcode 8.x to migrate the code to Swift 3.

![Captura de Pantalla 2019-09-14 a la(s) 13 04 19](https://user-images.githubusercontent.com/7443269/64912707-3323f380-d6f0-11e9-94db-8315b8647f86.png)

I'm using XCode 10.1 and macOS Mojave 10.14.5

**Comment by kingst** [comment]
This is strange, one of our test programs is objective C and I've been working closely with two large apps that are using this library and written in objective C and no one has experienced this error.

As far as I know our SDK only contains swift 4, 4.2, and 5 code with the appropriate gate to build correctly. The only difference I can see is that I'm using Xcode 10.3.

To help me reproduce this can you create a simple "hello world" app that shows the error and post it to github? Alternatively if you are able to post the source code for your actual app of course I'm happy to look at that, but oftentimes that isn't possible.

**Comment by josher93** [comment]
> This is strange, one of our test programs is objective C and I've been working closely with two large apps that are using this library and written in objective C and no one has experienced this error.
> 
> As far as I know our SDK only contains swift 4, 4.2, and 5 code with the appropriate gate to build correctly. The only difference I can see is that I'm using Xcode 10.3.
> 
> To help me reproduce this can you create a simple "hello world" app that shows the error and post it to github? Alternatively if you are able to post the source code for your actual app of course I'm happy to look at that, but oftentimes that isn't possible.

I solved my issue! Thank you. This is what I did:

- Updated Xcode to 10.3
- Removed some useless pods
- Set a Swift version language for CardScan in pod's target like this:
![Captura de Pantalla 2019-09-17 a la(s) 10 25 33](https://user-images.githubusercontent.com/7443269/65060971-27297300-d936-11e9-82e0-78d159566daa.png)

This solved my problem

**Comment by kingst** [comment]
👍
