### ISSUE TITLE
ScanViewController no 'configureWithApiKey' method

### ISSUE THREAD

**Issue by josher93** [getbouncer/cardscan-ios#79]
I'm configuring CardScan in an Objective-C project.  The documentation says:

> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
>     **[ScanViewController configureWithApiKey:@"YOUR_API_KEY_HERE"];**
>     return YES;
> }

I want to set the Key but there is no `configureWithApiKey` method:
![Captura de Pantalla 2019-09-18 a la(s) 10 26 56](https://user-images.githubusercontent.com/7443269/65167049-0b3dd400-d9ff-11e9-945a-5cad0900b27f.png)

Only `configure` method:
![Captura de Pantalla 2019-09-18 a la(s) 10 25 42](https://user-images.githubusercontent.com/7443269/65167010-fbbe8b00-d9fe-11e9-8895-eac84d11d088.png)

Where the key must be set?

**Comment by kingst** [comment]
We added this fairly recently, do you have the latest version of the library? The most recent Cocoapod is 1.0.5014

**Comment by josher93** [comment]
Ok, thank you! That solved my problem
