### ISSUE TITLE
cardholder name always coming out to be empty string

### ISSUE THREAD

**Issue by SandsHellCreations** [getbouncer/cardscan-ios#86]
cardholder name always coming out to be empty string

**Comment by kingst** [comment]
We haven't implemented name extraction yet.

**Comment by bstillitano** [comment]
Any ETA on implementing name functionality?

**Comment by jaimejiyepark** [comment]
Hello @bstillitano,
We're currently working on the ML side of name extraction, so it is difficult to give a concrete ETA. But we will have it soon so make sure to watch the repo for any updates!
