### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joergbirkhold** [getbouncer/cardscan-ios#96]
As read the license there is no limitation to use the sdk in commercial projects, as long as we do not require support or customizations?

**Comment by kingst** [comment]
Hello! Here's a link to [our license](https://github.com/getbouncer/cardscan-ios/blob/master/LICENSE), it's the BSD 3 clause open source license. I'm not a lawyer so I'm hesitant to comment on limitations here in github, but it's a fairly common and standard license and there should be a number of good resources available to learn about it.
