### ISSUE TITLE
Enhancement: Need to scan name from the Card.How can I achieve this?

### ISSUE THREAD

**Issue by pawanline** [getbouncer/cardscan-ios#98]

**Comment by kingst** [comment]
I saw that you submitted a PR, but it was kind of hard to tell what was going on because it included a bunch of our changes as well.

Can you explain a little more about what you have found in your testing? I'm open to this.

**Comment by pawanline** [comment]
First of all thanks for reply,Please ignore PR , I have submitted. during my testing, I found that I am unable to get name from the card scanned.I have also need of user name in my project implementation.
Now , I have get the name from the scanned card using VNRecognizeTextRequests and NSLinguisticTagger. I want to contribute to this project Please let me know from which branch I have to create pull request. Also let me know if anything required.

**Comment by kingst** [comment]
We added this feature recently, it's in master if you want to play with it now or you can wait until our next release, which I expect to go out next week.
